// Code generated by "esc -o ../../internal/resources/static.go -pkg resources -include=\\*.yaml -ignore=vendor/|.git|.generated|.idea ../.."; DO NOT EDIT.

package resources

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/internal/azure_devops/global/global-role-binding.template.yaml": {
		name:    "global-role-binding.template.yaml",
		local:   "../../internal/azure_devops/global/global-role-binding.template.yaml",
		size:    282,
		modtime: 1611324188,
		compressed: `
H4sIAAAAAAAC/3yOwU7DMAxA7/mK/MCKdkO5daGaeqCgFnad3NSAWRtHibMDU/4dDSqEhMTVfvZ7EOiA
MRF7o+MIroIsbxzpA4TYV6fbVBHfnLcjCmzVifxktJ1zEow9z7gjP5F/VQsKTCBglNYeFjT6ctm13V3b
7Y9dfd+UoiLP2OPLlYBA+8g5/KNUWv+R/fx237MNTAt5lfL4jk6SUZv1ZsB4Joe1c5y9/Eoamv7Q2uZY
W/vw3D2Vsu5SAPcFXFuHx9o2pXwGAAD//+SSO2YaAQAA
`,
	},

	"/internal/azure_devops/global/service-account.template.yaml": {
		name:    "service-account.template.yaml",
		local:   "../../internal/azure_devops/global/service-account.template.yaml",
		size:    100,
		modtime: 1611324188,
		compressed: `
H4sIAAAAAAAC/0osyAxLLSrOzM+zUigz5MrOzEuxUghOLSrLTE51TE7OL80r4cpNLUlMSSxJtOJSUMhL
zE21UqiuDnYNCvN0do13dHb2D/ULqa2FyhUXJCaDFfg5+roGBzg6u9bWAgIAAP//4dOwA2QAAAA=
`,
	},

	"/internal/azure_devops/scoped/namespace-cicd-binding.template.yaml": {
		name:    "namespace-cicd-binding.template.yaml",
		local:   "../../internal/azure_devops/scoped/namespace-cicd-binding.template.yaml",
		size:    302,
		modtime: 1611324188,
		compressed: `
H4sIAAAAAAAC/3zOsU7DMBDG8d1P4RdoUDfkLTVRlYGAEuhaXZwDjiZ3kX3uQNV3R6EV6tT1/vp0P5hp
hzGRsLOxh1BA1i+J9ANKwsXhMRUkD8d1jwprcyAenG1lxA3xQPxpJlQYQMEZaxkmdPZ02tTNU91s9035
XJ3P15BmCH91uXavpV9SlBFb/FjGMNM2Sp7vMIy1F4Afc1KMi+P/bbjcVjBMxCbl/huDJmdW102H8UgB
yxAks95ou6rd1b7al96/vDdvd8G/AQAA//+QExLKLgEAAA==
`,
	},

	"/internal/azure_devops/scoped/service-account.template.yaml": {
		name:    "service-account.template.yaml",
		local:   "../../internal/azure_devops/scoped/service-account.template.yaml",
		size:    100,
		modtime: 1611324188,
		compressed: `
H4sIAAAAAAAC/0osyAxLLSrOzM+zUigz5MrOzEuxUghOLSrLTE51TE7OL80r4cpNLUlMSSxJtOJSUMhL
zE21UqiuDnYNCvN0do13dHb2D/ULqa2FyhUXJCaDFfg5+roGBzg6u9bWAgIAAP//4dOwA2QAAAA=
`,
	},

	"/": {
		name:  "/",
		local: `../..`,
		isDir: true,
	},

	"/cmd": {
		name:  "cmd",
		local: `../../cmd`,
		isDir: true,
	},

	"/cmd/copsctl": {
		name:  "copsctl",
		local: `../../cmd/copsctl`,
		isDir: true,
	},

	"/internal": {
		name:  "internal",
		local: `../../internal`,
		isDir: true,
	},

	"/internal/adapters": {
		name:  "adapters",
		local: `../../internal/adapters`,
		isDir: true,
	},

	"/internal/adapters/azure_devops": {
		name:  "azure_devops",
		local: `../../internal/adapters/azure_devops`,
		isDir: true,
	},

	"/internal/adapters/kubernetes": {
		name:  "kubernetes",
		local: `../../internal/adapters/kubernetes`,
		isDir: true,
	},

	"/internal/azure_devops": {
		name:  "azure_devops",
		local: `../../internal/azure_devops`,
		isDir: true,
	},

	"/internal/azure_devops/global": {
		name:  "global",
		local: `../../internal/azure_devops/global`,
		isDir: true,
	},

	"/internal/azure_devops/scoped": {
		name:  "scoped",
		local: `../../internal/azure_devops/scoped`,
		isDir: true,
	},

	"/internal/common": {
		name:  "common",
		local: `../../internal/common`,
		isDir: true,
	},

	"/internal/common/commands": {
		name:  "commands",
		local: `../../internal/common/commands`,
		isDir: true,
	},

	"/internal/common/file_processing": {
		name:  "file_processing",
		local: `../../internal/common/file_processing`,
		isDir: true,
	},

	"/internal/common/logging": {
		name:  "logging",
		local: `../../internal/common/logging`,
		isDir: true,
	},

	"/internal/connection": {
		name:  "connection",
		local: `../../internal/connection`,
		isDir: true,
	},

	"/internal/namespace": {
		name:  "namespace",
		local: `../../internal/namespace`,
		isDir: true,
	},

	"/internal/resources": {
		name:  "resources",
		local: `../../internal/resources`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"../..": {},

	"../../cmd": {},

	"../../cmd/copsctl": {},

	"../../internal": {},

	"../../internal/adapters": {},

	"../../internal/adapters/azure_devops": {},

	"../../internal/adapters/kubernetes": {},

	"../../internal/azure_devops": {},

	"../../internal/azure_devops/global": {
		_escData["/internal/azure_devops/global/global-role-binding.template.yaml"],
		_escData["/internal/azure_devops/global/service-account.template.yaml"],
	},

	"../../internal/azure_devops/scoped": {
		_escData["/internal/azure_devops/scoped/namespace-cicd-binding.template.yaml"],
		_escData["/internal/azure_devops/scoped/service-account.template.yaml"],
	},

	"../../internal/common": {},

	"../../internal/common/commands": {},

	"../../internal/common/file_processing": {},

	"../../internal/common/logging": {},

	"../../internal/connection": {},

	"../../internal/namespace": {},

	"../../internal/resources": {},
}
