apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{BINDING_NAME}}
  namespace: {{NAMESPACE}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ROLE_NAME}}
subjects:
- kind: ServiceAccount
  name: {{SERVICE_ACCOUNT}}
  namespace: {{NAMESPACE}}