kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ROLE_NAME}}
  namespace: {{NAMESPACE}}
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [ "rolebindings", "roles" ]
  verbs: ["list", "get"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["", "extensions", "apps", "batch", "networking.k8s.io", "policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["*"]