environment:
  name: "?" # MANDATORY The name of the build environment. Name must be less or equal 12 char
  subscription_id: "?" # MANDATORY The id of the subscription where to provision the resources
  tenant_id: "?" # MANDATORY The id of the tenant where the subscription is located. Try to avoid cross tenant scenarios. Build and application infrastructure should be im same tenant.
  region: "francecentral" # MANDATORY. Make sure the core build infrastructure is deployed in different region than the infrastructure you plan to deploy with the created agentpool.

security:
  authorized_ip_ranges:
    cidrs:
    - "195.226.180.98" # CP primary static IP
    - "87.128.42.228" # CP secondary static IP
  # OPTIONAL Role assignments can be used to apply role assignments here for resources with lifecycle external to build agent release process
  # Given roles and scopes will be assigned to managed identity created. Identity is used in build agent vmss
  role_assignments:
    - scope: "?" # Azure resource id for the scope the role should be applied e.g. /subscriptions/<subscription_id>
      role_definition_name: "?" # Role definition to be applied e.g. Reader

azure_devops:
  # MANDATORY Personal Access Token to create agent pool with permissions:
  # - Agent Pools (Read & manage)
  # - Service Connections (Read, query & manage)
  # - Project and Team (Read)
  pat_secret: ""
  organisation_name: "" # MANDATORY OrganisationName in azure devops
  project_name: "" # MANDATORY Project name in azure devops
  pool_settings:
    desired_idle: 0 # MANDATORY Number of agents to have ready waiting for jobs. Scale down to 0 reduces cost ( expected starttime when no agents running < 3min )
    max_capacity: 5 # MANDATORY Maximum number of agents that will exist in the elastic pool if required
    time_to_live_minutes: 30 # MANDATORY The minimum time in minutes to keep idle agents alive
