/*      !!!  A U T O G E N E R A T E D  !!!

This file is autogenerated based on ./.corebuild.template.yaml and should not be manipulated manually

For generation use ./.corebuild.template.yaml and copy paste to https://christiangottinger.github.io/yaml-to-go/
- GoSerializationTags should be: 	yaml, json
- GoTypeName should be: 			SourceConfig
- InlineTypeDefinitions should be:  false

Make sure you do not use environment config file for generation

		!!!  D O   N O T   T O U C H  !!!
*/

package configuration

type SourceConfig struct {
	Environment Environment `yaml:"environment" json:"environment"`
	Security    Security    `yaml:"security" json:"security"`
	AzureDevops AzureDevops `yaml:"azure_devops" json:"azure_devops"`
}
type Environment struct {
	Name           string `yaml:"name" json:"name"`
	SubscriptionID string `yaml:"subscription_id" json:"subscription_id"`
	TenantID       string `yaml:"tenant_id" json:"tenant_id"`
	Region         string `yaml:"region" json:"region"`
	NodeDiskSizeGb int    `yaml:"node_disk_size_gb" json:"node_disk_size_gb"`
}
type AuthorizedIPRanges struct {
	Cidrs []string `yaml:"cidrs" json:"cidrs"`
}
type RoleAssignments struct {
	Scope              string `yaml:"scope" json:"scope"`
	RoleDefinitionName string `yaml:"role_definition_name" json:"role_definition_name"`
}
type Security struct {
	AuthorizedIPRanges AuthorizedIPRanges `yaml:"authorized_ip_ranges" json:"authorized_ip_ranges"`
	RoleAssignments    []RoleAssignments  `yaml:"role_assignments" json:"role_assignments"`
}
type PoolSettings struct {
	DesiredIdle       int `yaml:"desired_idle" json:"desired_idle"`
	MaxCapacity       int `yaml:"max_capacity" json:"max_capacity"`
	TimeToLiveMinutes int `yaml:"time_to_live_minutes" json:"time_to_live_minutes"`
}
type AzureDevops struct {
	PatSecret        string       `yaml:"pat_secret" json:"pat_secret"`
	OrganisationName string       `yaml:"organisation_name" json:"organisation_name"`
	ProjectName      string       `yaml:"project_name" json:"project_name"`
	PoolSettings     PoolSettings `yaml:"pool_settings" json:"pool_settings"`
}
